config/routes.rb
Tweetpulse::Application.routes.draw do
  
  resources :searches

  resources :tweets

  match '/auth/:provider/callback' => 'authentications#create' 
  resources :authentications

  devise_for :users

  resources :user_terms

  resources :hashtag_terms

  resources :keyword_terms

  resources :terms
  
  resources :twitter_users

  root :to => 'dashboard#index'
  get "/dashboard", :as => "dashboard", :to => "dashboard#index"
  
  get "/dashboard/:search_id/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  get "/dashboard/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  
  get "/searches/:search_id/refresh", :as => "refresh_search_results", :to => "searches#refresh_results"
  get "/twitter_users/:twitter_user_id/refresh", :as => "refresh_twitter_user_results", :to => "twitter_users#refresh_results"
  get "/tweets/:tweet_id/refresh", :as => "refresh_tweet_results", :to => "tweets#refresh_results"

  
  get "/auth/twitter", :as => "twitter_auth"
  
  get "/tweets/:tweet_id/tooltip", :as => "tweet_tooltip", :to => "tweets#show_tooltip"
  get "/twitter_users/:twitter_user_id/tooltip", :as => "twitter_user_tooltip", :to => "twitter_users#show_tooltip"
  get "/retweets/:id/tooltip", :as => "retweet_tooltip", :to => "retweets#show_tooltip"
  
  get "/searches/:id/download", :as => "csv_search", :to => "searches#show", :constraints => {:format => /(csv)/}

end

app/models/keyword_term.rb
class KeywordTerm < Term
  
  def get_tweets
    self.user.twitter.search(self.text, :count => 5).results.map do |status|
      self.tweets.create(:tweet_id => status.id, :from_user => status.from_user, :text => status.text)
    end
    self.tweets
  end
  
end

app/controllers/keyword_terms_controller.rb
class KeywordTermsController < ApplicationController
  # GET /keyword_terms
  # GET /keyword_terms.json
  def index
    @keyword_terms = KeywordTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keyword_terms }
    end
  end

  # GET /keyword_terms/1
  # GET /keyword_terms/1.json
  def show
    @keyword_term = KeywordTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @keyword_term }
    end
  end

  # GET /keyword_terms/new
  # GET /keyword_terms/new.json
  def new
    @keyword_term = KeywordTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @keyword_term }
    end
  end

  # GET /keyword_terms/1/edit
  def edit
    @keyword_term = KeywordTerm.find(params[:id])
  end

  # POST /keyword_terms
  # POST /keyword_terms.json
  def create
    @keyword_term = KeywordTerm.new(params[:keyword_term])

    respond_to do |format|
      if @keyword_term.save
        format.html { redirect_to @keyword_term, notice: 'Keyword term was successfully created.' }
        format.json { render json: @keyword_term, status: :created, location: @keyword_term }
      else
        format.html { render action: "new" }
        format.json { render json: @keyword_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keyword_terms/1
  # PUT /keyword_terms/1.json
  def update
    @keyword_term = KeywordTerm.find(params[:id])

    respond_to do |format|
      if @keyword_term.update_attributes(params[:keyword_term])
        format.html { redirect_to @keyword_term, notice: 'Keyword term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @keyword_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keyword_terms/1
  # DELETE /keyword_terms/1.json
  def destroy
    @keyword_term = KeywordTerm.find(params[:id])
    @keyword_term.destroy

    respond_to do |format|
      format.html { redirect_to keyword_terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/keyword_terms_helper.rb
module KeywordTermsHelper
end

app/views/keyword_terms/_form.html.erb
<%= simple_form_for(@keyword_term) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/keyword_terms/edit.html.erb
<h1>Editing keyword_term</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword_term %> |
<%= link_to 'Back', keyword_terms_path %>

app/views/keyword_terms/index.html.erb
<h1>Listing keyword_terms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keyword_terms.each do |keyword_term| %>
  <tr>
    <td><%= link_to 'Show', keyword_term %></td>
    <td><%= link_to 'Edit', edit_keyword_term_path(keyword_term) %></td>
    <td><%= link_to 'Destroy', keyword_term, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword term', new_keyword_term_path %>

app/views/keyword_terms/new.html.erb
<h1>New keyword_term</h1>

<%= render 'form' %>

<%= link_to 'Back', keyword_terms_path %>

app/views/keyword_terms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_keyword_term_path(@keyword_term) %> |
<%= link_to 'Back', keyword_terms_path %>