config/routes.rb
Tweetpulse::Application.routes.draw do
  
  resources :searches

  resources :tweets

  match '/auth/:provider/callback' => 'authentications#create' 
  resources :authentications

  devise_for :users

  resources :user_terms

  resources :hashtag_terms

  resources :keyword_terms

  resources :terms
  
  resources :twitter_users

  root :to => 'dashboard#index'
  get "/dashboard", :as => "dashboard", :to => "dashboard#index"
  
  get "/dashboard/:search_id/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  get "/dashboard/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  
  get "/searches/:search_id/refresh", :as => "refresh_search_results", :to => "searches#refresh_results"
  get "/twitter_users/:twitter_user_id/refresh", :as => "refresh_twitter_user_results", :to => "twitter_users#refresh_results"
  get "/tweets/:tweet_id/refresh", :as => "refresh_tweet_results", :to => "tweets#refresh_results"

  
  get "/auth/twitter", :as => "twitter_auth"
  
  get "/tweets/:tweet_id/tooltip", :as => "tweet_tooltip", :to => "tweets#show_tooltip"
  get "/twitter_users/:twitter_user_id/tooltip", :as => "twitter_user_tooltip", :to => "twitter_users#show_tooltip"
  get "/retweets/:id/tooltip", :as => "retweet_tooltip", :to => "retweets#show_tooltip"
  
  get "/searches/:id/download", :as => "csv_search", :to => "searches#show", :constraints => {:format => /(csv)/}

end

app/models/user_term.rb
class UserTerm < Term
  
  def get_tweets
    self.user.twitter.search("from:#{self.text}", :count => 5).results.map do |status|
      self.tweets.create(:tweet_id => status.id, :from_user => status.from_user, :text => status.text)
    end
    self.tweets
  end
  
  def to_s
    '@' + self.text
  end
end

app/controllers/user_terms_controller.rb
class UserTermsController < ApplicationController
  # GET /user_terms
  # GET /user_terms.json
  def index
    @user_terms = UserTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_terms }
    end
  end

  # GET /user_terms/1
  # GET /user_terms/1.json
  def show
    @user_term = UserTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_term }
    end
  end

  # GET /user_terms/new
  # GET /user_terms/new.json
  def new
    @user_term = UserTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_term }
    end
  end

  # GET /user_terms/1/edit
  def edit
    @user_term = UserTerm.find(params[:id])
  end

  # POST /user_terms
  # POST /user_terms.json
  def create
    @user_term = UserTerm.new(params[:user_term])

    respond_to do |format|
      if @user_term.save
        format.html { redirect_to @user_term, notice: 'User term was successfully created.' }
        format.json { render json: @user_term, status: :created, location: @user_term }
      else
        format.html { render action: "new" }
        format.json { render json: @user_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_terms/1
  # PUT /user_terms/1.json
  def update
    @user_term = UserTerm.find(params[:id])

    respond_to do |format|
      if @user_term.update_attributes(params[:user_term])
        format.html { redirect_to @user_term, notice: 'User term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_terms/1
  # DELETE /user_terms/1.json
  def destroy
    @user_term = UserTerm.find(params[:id])
    @user_term.destroy

    respond_to do |format|
      format.html { redirect_to user_terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_terms_helper.rb
module UserTermsHelper
end

app/views/user_terms/_form.html.erb
<%= simple_form_for(@user_term) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_terms/edit.html.erb
<h1>Editing user_term</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_term %> |
<%= link_to 'Back', user_terms_path %>

app/views/user_terms/index.html.erb
<h1>Listing user_terms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_terms.each do |user_term| %>
  <tr>
    <td><%= link_to 'Show', user_term %></td>
    <td><%= link_to 'Edit', edit_user_term_path(user_term) %></td>
    <td><%= link_to 'Destroy', user_term, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User term', new_user_term_path %>

app/views/user_terms/new.html.erb
<h1>New user_term</h1>

<%= render 'form' %>

<%= link_to 'Back', user_terms_path %>

app/views/user_terms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_term_path(@user_term) %> |
<%= link_to 'Back', user_terms_path %>