config/routes.rb
Tweetpulse::Application.routes.draw do
  
  resources :searches

  resources :tweets

  match '/auth/:provider/callback' => 'authentications#create' 
  resources :authentications

  devise_for :users

  resources :user_terms

  resources :hashtag_terms

  resources :keyword_terms

  resources :terms
  
  resources :twitter_users

  root :to => 'dashboard#index'
  get "/dashboard", :as => "dashboard", :to => "dashboard#index"
  
  get "/dashboard/:search_id/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  get "/dashboard/refresh", :as => "refresh_dashboard", :to => "dashboard#refresh_graphs"
  
  get "/searches/:search_id/refresh", :as => "refresh_search_results", :to => "searches#refresh_results"
  get "/twitter_users/:twitter_user_id/refresh", :as => "refresh_twitter_user_results", :to => "twitter_users#refresh_results"
  get "/tweets/:tweet_id/refresh", :as => "refresh_tweet_results", :to => "tweets#refresh_results"

  
  get "/auth/twitter", :as => "twitter_auth"
  
  get "/tweets/:tweet_id/tooltip", :as => "tweet_tooltip", :to => "tweets#show_tooltip"
  get "/twitter_users/:twitter_user_id/tooltip", :as => "twitter_user_tooltip", :to => "twitter_users#show_tooltip"
  get "/retweets/:id/tooltip", :as => "retweet_tooltip", :to => "retweets#show_tooltip"
  
  get "/searches/:id/download", :as => "csv_search", :to => "searches#show", :constraints => {:format => /(csv)/}

end

app/models/hashtag_term.rb
class HashtagTerm < Term
  
  def get_tweets
    self.user.twitter.search("#" + self.text, :count => 5).results.map do |status|
      self.tweets.create(:tweet_id => status.id, :from_user => status.from_user, :text => status.text)
    end
    self.tweets
  end
  
  def to_s
    "#" + self.text
  end
end

app/controllers/hashtag_terms_controller.rb
class HashtagTermsController < ApplicationController
  # GET /hashtag_terms
  # GET /hashtag_terms.json
  def index
    @hashtag_terms = HashtagTerm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hashtag_terms }
    end
  end

  # GET /hashtag_terms/1
  # GET /hashtag_terms/1.json
  def show
    @hashtag_term = HashtagTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hashtag_term }
    end
  end

  # GET /hashtag_terms/new
  # GET /hashtag_terms/new.json
  def new
    @hashtag_term = HashtagTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hashtag_term }
    end
  end

  # GET /hashtag_terms/1/edit
  def edit
    @hashtag_term = HashtagTerm.find(params[:id])
  end

  # POST /hashtag_terms
  # POST /hashtag_terms.json
  def create
    @hashtag_term = HashtagTerm.new(params[:hashtag_term])

    respond_to do |format|
      if @hashtag_term.save
        format.html { redirect_to @hashtag_term, notice: 'Hashtag term was successfully created.' }
        format.json { render json: @hashtag_term, status: :created, location: @hashtag_term }
      else
        format.html { render action: "new" }
        format.json { render json: @hashtag_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hashtag_terms/1
  # PUT /hashtag_terms/1.json
  def update
    @hashtag_term = HashtagTerm.find(params[:id])

    respond_to do |format|
      if @hashtag_term.update_attributes(params[:hashtag_term])
        format.html { redirect_to @hashtag_term, notice: 'Hashtag term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hashtag_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtag_terms/1
  # DELETE /hashtag_terms/1.json
  def destroy
    @hashtag_term = HashtagTerm.find(params[:id])
    @hashtag_term.destroy

    respond_to do |format|
      format.html { redirect_to hashtag_terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/hashtag_terms_helper.rb
module HashtagTermsHelper
end

app/views/hashtag_terms/_form.html.erb
<%= simple_form_for(@hashtag_term) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hashtag_terms/edit.html.erb
<h1>Editing hashtag_term</h1>

<%= render 'form' %>

<%= link_to 'Show', @hashtag_term %> |
<%= link_to 'Back', hashtag_terms_path %>

app/views/hashtag_terms/index.html.erb
<h1>Listing hashtag_terms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hashtag_terms.each do |hashtag_term| %>
  <tr>
    <td><%= link_to 'Show', hashtag_term %></td>
    <td><%= link_to 'Edit', edit_hashtag_term_path(hashtag_term) %></td>
    <td><%= link_to 'Destroy', hashtag_term, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hashtag term', new_hashtag_term_path %>

app/views/hashtag_terms/new.html.erb
<h1>New hashtag_term</h1>

<%= render 'form' %>

<%= link_to 'Back', hashtag_terms_path %>

app/views/hashtag_terms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_hashtag_term_path(@hashtag_term) %> |
<%= link_to 'Back', hashtag_terms_path %>